openapi: 3.0.1
info:
  title: Mocker API
  description: API describing how to interact with the mocker application.
  version: 1.0.0
servers:
  - url: http://localhost:8080/v1
    description: Local URL for the v1 of the application.
  - url: https://localhost:8090/v1
    description: Alternative local URL for the v1 of the application.
components:
  schemas:
    Mapping:
      properties:
        name:
          type: string
          description: Used to uniquely identify this mapping. Can be used for search or as an easy way to identify it.
        request:
          $ref: '#/components/schemas/Request'
        response:
          $ref: '#/components/schemas/Response'
      required:
        - name
        - request
        - response
    Request:
      properties:
        endpoint:
          type: string
          description: Endpoint for which the mock is created. Can contain multiple levels using / as separator.
        method:
          type: string
          description: Http method for which the mock is created. Possible values are GET, POST, PUT, DELETE etc.
      required:
        - endpoint
        - method
    Response:
      properties:
        status:
          type: integer
          description: Http status code for the response. Possible values are 200, 404, 500 etc.
        body:
          type: string
          description: The actual content of the reponse. An example response could contain a body with a JSON, HTML etc.
        headers:
          type: array
          description: Http headers that are required for the response. Any header name is allowed.
          items:
            type: object
            properties:
              key:
                type: string
              value:
                type: string
      required:
        - status
        - body
tags:
- name: "Mapping"
paths:
  /api/mappings:
    post:
      tags:
        - "Mapping"
      summary: Create a new mapping.
      description: Create a new mapping based on the given details.
      parameters:
        - name: X-Application
          description: Identification value for the application making the request.
          required: true
          in: header
          schema:
            type: string
      requestBody:
        description: Contains details about the mapping and what request to map to a response.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mapping'
      responses:
        201:
          description: Created
          content: {}
        400:
          description: Bab Request
          content: {}
        500:
          description: Internal Server Error
          content: {}
    get:
      tags:
        - "Mapping"
      summary: List of all mappings.
      description: Returns a list of all mappings in this mock server using pagination.
      parameters:
        - name: X-Application
          description: Identification value for the application making the request.
          required: true
          in: header
          schema:
            type: string
        - name: page
          description: Pagination parameter used to specify which page to return (default 0).
          required: false
          in: query
          schema:
            type: integer
        - name: size
          description: Pagination parameter used to specify the number of results per page (default 20).
          required: false
          in: query
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Mapping'
  /api/mappings/{name}:
    get:
      tags:
        - "Mapping"
      summary: Get the mapping with the given name.
      description: Returns the exact mapping containing the given name.
      parameters:
        - name: X-Application
          description: Identification value for the application making the request.
          required: true
          in: header
          schema:
            type: string
        - name: name
          description: Actual unique name to look for.
          required: true
          in: path
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Mapping'
        404:
          description: Not Found
          content: {}
    put:
      tags:
        - "Mapping"
      summary: Update the mapping with the given name, request is idempotent.
      description: Will update an existing mapping identified by the name.
      parameters:
        - name: X-Application
          description: Identification value for the application making the request.
          required: true
          in: header
          schema:
            type: string
        - name: name
          description: Actual unique name to look for.
          required: true
          in: path
          schema:
            type: string
      requestBody:
        description: Contains details about the mapping and what to update about it.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mapping'
      responses:
        200:
          description: OK
          content: {}
        400:
          description: Bab Request
          content: {}
        404:
          description: Not Found
          content: {}