name: Mocker CI

on:
  push:
    branches:    
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        mvn -B clean package -DskipTests --file pom.xml
        mkdir artifacts && cp target/mocker*.jar artifacts
    
    - name: Persist Mocker artifact
      uses: actions/upload-artifact@v3
      with:
        name: mocker
        path: artifacts
